
webhook:
  fullnameOverride: argocd-webhook
  ### override app name. if not exist, use .Chart.Name
  # appNameOverride:

  replicaCount: 1

  env:
    - name: ARGOCD_BIN_PATH
      value: argocd
    - name: ARGOCD_PASSWORD
      value: your-argocd-password #change to your argocd password
    - name: ARGOCD_SERVER_HOST
      value: IP_OR_DOMAIN:PORT #change to your argocd host
    - name: ARGOCD_USERNAME
      value: admin #your argocd username

  service:
    type: NodePort
    port: 31001

  image:
    registry: docker.io
    repository: jibill13/argocd-webhook
    ### If tag is not exist, use .Chart.appVersion
    # tag:
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "10m"
      memory: "30Mi"